### ISSUE TITLE
Please add Applied Energistics 2

### ISSUE THREAD

**Issue by Evolinox** [CakeOfPain/MC-Mods-Server#1]
Pls add, thx

**Comment by CakeOfPain** [comment]
![meme](https://preview.redd.it/cer-ule-tus-quartz-v0-q33atatwulua1.gif?format=png8&s=434ea25f4edaefdb2fd487c6b4ef8de882a02d83)

**Comment by CakeOfPain** [comment]
I will do my best to add it.

**Comment by CakeOfPain** [comment]
Yay, I did it!
